account/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.index,name='index'),
    path('user_register',views.user_register,name='user_register'),
    path('employee_register',views.employee_register,name='employee_register'),
    path('user_login',views.user_login,name='user_login'),
    path('user_logout',views.user_logout,name='user_logout'),
    path('dashboard',views.dashboard,name='dashboard'),


    path('booking_services',views.booking_services,name='booking_services'),
    path('my_bookings',views.my_bookings,name='my_bookings'),
    path('allotted_work',views.allotted_work,name='allotted_work'),

    path('send_complaint',views.send_complaint,name='send_complaint'),
    path('my_complaints',views.my_complaints,name='my_complaints'),
    path('allotted_complaints',views.allotted_complaints,name='allotted_complaints'),


    path('view_service_booking',views.view_service_booking,name='view_service_booking'),

    path('assign_employee/<int:id>',views.assign_employee,name='assign_employee'),

    path('update_booking/<int:id>',views.update_booking,name='update_booking'),
    path('change_status',views.change_status,name='change_status'),

    

    

]

payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('payment/<int:booking_id>',views.payment,name='payment'),
    path('payment-status', views.payment_status, name='payment-status'),


 
    
]

solar_management/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('payment/',include('payment.urls')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.http import request
from phonenumber_field.modelfields import PhoneNumberField

from django.utils import timezone

# Create your models here.

class UserRegister(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    phone=PhoneNumberField()
    location=models.CharField(max_length=50)
    status=models.BooleanField(default=False)
    def __str__(self):
        return str(self.user.username)


class EmployeeRegister(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    phone=PhoneNumberField()
    location=models.CharField(max_length=50)
    status=models.BooleanField(default=False)
    available='available'
    not_available='not_available'
    availabilty_statuses=[
        (available,'available'),
        (not_available,'not_available')
    ]
    availabilty_status=models.CharField(max_length=50,choices=availabilty_statuses,default=available)
    def __str__(self):
        return str(self.user.username)






class BatteryBrand(models.Model):
    brand=models.CharField(max_length=50)
    def __str__(self):
        return str(self.brand)


class BatteryType(models.Model):
    type=models.CharField(max_length=50)
    brand=models.ForeignKey(BatteryBrand,on_delete=models.CASCADE,null=True,blank=True)
    price=models.IntegerField(null=True,blank=True)
    def __str__(self):
        return str(self.type)



class Booking(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    employee=models.ForeignKey(EmployeeRegister,on_delete=models.CASCADE,null=True,blank=True)
    user_details=models.ForeignKey(UserRegister,on_delete=models.CASCADE,null=True,blank=True)
    location=models.CharField(max_length=50)
    wanted_date=models.DateField(default=timezone.now)
    processing='processing'
    accepted='accepted'
    rejected='rejected'
    booking_statuses=[
        
        (processing,'processing'),
        (accepted,'accepted'),
        (rejected,'rejected')

    ]
    booking_status=models.CharField(max_length=50,choices=booking_statuses,default=processing)
    
    battery_type=models.ForeignKey(BatteryType,on_delete=models.CASCADE,null=True,blank=True)
    battery_brand=models.ForeignKey(BatteryBrand,on_delete=models.CASCADE,null=True,blank=True)
    unit=models.IntegerField()
    date=models.DateTimeField(default=timezone.now)
    amount=models.IntegerField(default=500)
    paid=models.BooleanField(default=False)
    def __str__(self):
        return str(self.user.username)



class Complaint(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    employee=models.ForeignKey(EmployeeRegister,on_delete=models.CASCADE,null=True,blank=True)
    user_details=models.ForeignKey(UserRegister,on_delete=models.CASCADE,null=True,blank=True)
    complaint=models.TextField()
    date=models.DateTimeField(default=timezone.now)
    def __str__(self):
        return str(self.user.username)

    

account/forms.py
from django import forms
from django.db.models import fields
from . models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    username=forms.CharField(help_text=None,label='Username')
    password1=forms.CharField(help_text=None,widget=forms.PasswordInput,label='Password')
    password2=forms.CharField(help_text=None,widget=forms.PasswordInput,label='Confirm Password')
    class Meta:
        model=User
        fields=('username','email','password1','password2')
        labels=('password1','password','password2','confirm password')


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model=UserRegister
        fields=('phone','location')



class EmployeeRegistrationForm(forms.ModelForm):
    class Meta:
        model=EmployeeRegister
        fields=('phone','location')


class BookingForm(forms.ModelForm):
    
    wanted_date=forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model=Booking
        fields=('location','wanted_date','battery_type','battery_brand','unit')



class BookingFormUpdate(forms.ModelForm):
    
    class Meta:
        model=Booking
        fields=('booking_status','amount')

    
class ComplaintForm(forms.ModelForm):
    complaint=forms.Textarea()
    class Meta:
        model=Complaint
        fields=('complaint',)



class EstimateForm(forms.ModelForm):
    watt=forms.IntegerField()
    class Meta:
        model=BatteryType
        fields=('type','brand','watt')





class AvailabilityForm(forms.ModelForm):
    class Meta:
        model=EmployeeRegister
        fields=('availabilty_status',)

account/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from . models import *
from . forms import *
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages


from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.dispatch import receiver

# Create your views here.
def index(request):
    battery=BatteryType.objects.all()
    print(battery)
    if request.method=="POST":
        type=request.POST.get('type')
        brand=request.POST.get('brand')
        watt=request.POST.get('watt')
        try:
            battery_price=BatteryType.objects.get(type=type,brand=brand)
            print(battery_price.price)
            estimate_price=int(watt)*3+int(battery_price.price)
            print(estimate_price)
            battery=BatteryType.objects.all()
            return render(request,'index.html',{'battery':battery,'estimate_price':estimate_price})
        except:
            return render(request,'index.html',{'battery':battery})


    return render(request,'index.html',{'battery':battery})


def user_register(request):
    reg=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        user_registration_form=UserRegistrationForm(data=request.POST)
        if user_form.is_valid() and user_registration_form.is_valid():
            user=user_form.save()
            user.save()
            profile=user_registration_form.save(commit=False)
            profile.user=user
            profile.save()

            reg=True
            return redirect('user_login')
        else:
            HttpResponse("invalid form")
    else:
         user_form=UserForm()
         user_registration_form=UserRegistrationForm()
    return render(request,'user_register.html',{'register':reg,'user_form':user_form,'user_registration_form':user_registration_form})



def employee_register(request):
    reg=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        employee_registration_form=EmployeeRegistrationForm(data=request.POST)
        if user_form.is_valid() and employee_registration_form.is_valid():
            user=user_form.save()
            user.save()
            profile=employee_registration_form.save(commit=False)
            profile.user=user
            profile.save()

            reg=True
            return redirect('user_login')
        else:
            HttpResponse("invalid form")
    else:
         user_form=UserForm()
         employee_registration_form=EmployeeRegistrationForm()
    return render(request,'employee_register.html',{'register':reg,'user_form':user_form,'employee_registration_form':employee_registration_form})


def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username,password=password)

        try:
            user1=UserRegister.objects.get(user=user)
            print(user1)
        except:
            pass
            
        try:
            user2=EmployeeRegister.objects.get(user=user)
        except:
            pass

        if user:
            if user.is_active:
                try:
                    if user1:
                        active=UserRegister.objects.all().filter(user_id=user.id,status=True)
                        if active:
                            login(request,user)
                            return HttpResponseRedirect(reverse('dashboard'))
                        else:
                            return HttpResponse("Waiting for approval")
                except:
                    pass

                try:
                    if user2:
                        active=EmployeeRegister.objects.all().filter(user_id=user.id,status=True)
                        if active:
                            login(request,user)
                            return HttpResponseRedirect(reverse('dashboard'))
                        else:
                            return HttpResponse("Waiting for approval")
                except:
                    pass

                try:
                    if user.is_superuser:
                        login(request,user)
                        return HttpResponseRedirect(reverse('dashboard'))
                    else:
                        return HttpResponse("Waiting for approval")
                except:
                    pass                
            else:
                return HttpResponse("Not active")
        else:
            return HttpResponse("Invalid username or password")
    else: 
        return render(request,'login.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect('index')


def dashboard(request):
    return render(request,'dashboard.html')



def booking_services(request):
    
    if request.method=="POST":
        booking_form=BookingForm(request.POST)
        if booking_form.is_valid():
            user_details=UserRegister.objects.get(user=request.user)
            print(user_details)
            cp=Booking(user=request.user,user_details=user_details,location=booking_form.cleaned_data['location'],wanted_date=booking_form.cleaned_data['wanted_date'],
            battery_type=booking_form.cleaned_data['battery_type'],battery_brand=booking_form.cleaned_data['battery_brand'],unit=booking_form.cleaned_data['unit'])
            cp.save()

            
            return render(request,'booking_form.html',{'msg':'successfully added request'})
        else:
            return HttpResponse("Invalid form")
    booking_form=BookingForm()
    return render(request,'booking_form.html',{'form':booking_form})



def view_service_booking(request):
    bookings=Booking.objects.filter(employee=None).order_by('-id')
    return render(request,'view_all_bookings.html',{'bookings':bookings})


def my_bookings(request):
    my_booking=Booking.objects.filter(user=request.user)
    print(my_booking)
    return render(request,'my_bookings.html',{'my_booking':my_booking})


def allotted_work(request):
    
    employee=EmployeeRegister.objects.get(user=request.user)
    try:
        my_work=Booking.objects.filter(employee=employee)
    except:
        pass
    return render(request,'my_works.html',{'my_work':my_work})


def send_complaint(request):
    if request.method=="POST":
        complaint_form=ComplaintForm(request.POST)
        if complaint_form.is_valid():
            user_details=UserRegister.objects.get(user=request.user)
            print(user_details)
            cp=Complaint(user=request.user,user_details=user_details,complaint=complaint_form.cleaned_data['complaint'])
            cp.save()

            
            return render(request,'complaint_form.html',{'msg':'successfully added request'})
        else:
            return HttpResponse("Invalid form")
    complaint_form=ComplaintForm()
    return render(request,'complaint_form.html',{'form':complaint_form})



def my_complaints(request):
    my_complaint=Complaint.objects.filter(user=request.user)
    print(my_complaint)
    return render(request,'my_complaint.html',{'my_complaint':my_complaint})


def allotted_complaints(request):
    employee=EmployeeRegister.objects.get(user=request.user)
    try:
        my_complain=Complaint.objects.filter(employee=employee)
    except:
        pass
    return render(request,'allotted_complaint.html',{'my_complain':my_complain})





def assign_employee(request,id):
    available_employees=EmployeeRegister.objects.filter(availabilty_status='available')
    booking=Booking.objects.get(id=id)
    if request.method=="POST":
        available_employees=EmployeeRegister.objects.filter(availabilty_status='available')
        
        employee=request.POST.get('employee')
        print(employee)
        employee=EmployeeRegister.objects.get(id=employee)
        requirement=Booking.objects.update_or_create(id=id,
        defaults={'employee':employee}
        )
        return redirect('view_service_booking')

    return render(request,'assign_employee.html',{'available_employees':available_employees})



def update_booking(request,id):
    booking=Booking.objects.get(id=id)
    print(booking)
    update_booking_form=BookingFormUpdate(instance=booking)
    if request.method=="POST":
        update_booking_form=BookingFormUpdate(request.POST,request.FILES,instance=booking)
        update_booking_form.save()
        return redirect('allotted_work')
    return render(request,'booking_form.html',{'form':update_booking_form})



def change_status(request):
    my_volunteer=EmployeeRegister.objects.get(user=request.user)
    print(my_volunteer.availabilty_status)
    if request.method=="POST":
        my_volunteer=EmployeeRegister.objects.get(user=request.user)
        update_form=AvailabilityForm(request.POST,instance=my_volunteer)
        #print(my_volunteer.availability_status)
        if update_form.is_valid():
            update_form.save()
            
            messages.success(request,f'Your Account has been Updated')
            return redirect('dashboard')
    else:
        update_form=AvailabilityForm(instance=my_volunteer.user)
        
    context={
        'update_form':update_form,
        
    }
    return render(request,'update_employee_availability.html',context)



def estimate_price(request):
    battery=BatteryType.objects.all()
    print(battery)
    # if request.method=="POST":


        
        
           
            

            
        
   
    return render(request,'index.html',{'battery':battery})

account/templates/allotted_complaint.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="table-responsive table-shadow" style="background-color: bisque;">
    
  {% if my_complain %}
  <table class="table">
        <thead>
          <tr>
            <!-- <th scope="col">#</th> -->
            <th scope="col">User</th>
            <th scope="col">Phone</th>
           
            <th scope="col">Location</th>
            <th scope="col">Complaint</th>
            
            <th scope="col">Date</th>
          </tr>
        </thead>
        <tbody>
            {% for i in my_complain %}
          <tr style="background-color: #d9a3a3;">

            <td>{{ i.user.username}}</td>
            <td>{{ i.user_details.phone}}</td>
            
            <td>{{ i.user_details.location}}</td>
            <td>{{ i.complaint}}</td>
            
            
            
            <td>{{ i.date }}</td>

           
          </tr>

          {% endfor %}

        </tbody>

  </table>
  {% else %}

  <span>No Complaint can be found...</span>
  {% endif %}

</div>

{% endblock %}

account/templates/assign_employee.html
{% extends 'dashboard.html' %}


{% block content %}


<div>

    <form action="" method="POST"> 
        {% csrf_token %}
        
        <label for="employee" >Select Employee: </label> <select name="employee" >
            {% for i in available_employees %}
            <option value="{{i.id}}" name="employee">{{i.user.username}}</option>
            {% endfor %}
        </select>
        <input type="submit" value='Assign'>
    
    </form>
    
    
    
    
    </div>



{% endblock %}

account/templates/booking_form.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}


{% block content %}


<div style="padding-left: 2rem;padding-top: 2rem;padding-bottom: 1em;background-color: #c9c1b1;">

    <h2>Booking form</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        
        
        <input type="submit" value="SEND" style="background-color: #3e36c3;color: white;margin-top: 1em;">

    </form>
</div>

{% endblock %}

account/templates/complaint_form.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}


{% block content %}


<div style="padding-left: 2rem;padding-top: 2rem;padding-bottom: 1em;background-color: #c9c1b1;">

    <h2>Complaint form</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{form|crispy}}
        
        
        <input type="submit" value="SEND" style="background-color: #3e36c3;color: white;margin-top: 1em;">

    </form>
</div>

{% endblock %}

account/templates/dashboard.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<head>
<title>Visitors an Admin Panel Category Bootstrap Responsive Website Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- bootstrap-css -->
<link rel="stylesheet" href="static/css/bootstrap.min.css" >
<!-- //bootstrap-css -->
<!-- Custom CSS -->
<link href="static/css/style1.css" rel='stylesheet' type='text/css' />
<link href="static/css/style-responsive.css" rel="stylesheet"/>
<!-- font CSS -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<!-- font-awesome icons -->
<link rel="stylesheet" href="static/css/font.css" type="text/css"/>
<link href="static/css/font-awesome.css" rel="stylesheet"> 
<link rel="stylesheet" href="static/css/morris.css" type="text/css"/>
<!-- calendar -->
<link rel="stylesheet" href="static/css/monthly.css">
<!-- //calendar -->
<!-- //font-awesome icons -->
<script src="static/js/jquery2.0.3.min.js"></script>
<script src="static/js/raphael-min.js"></script>
<script src="static/js/morris.js"></script>
</head>
<body>
<section id="container">
<!--header start-->
<header class="header  clearfix">
<!--logo start-->
<div class="brand">
    <a href="{% url 'index' %}" class="logo">
        SOLAR
    </a>
    <div class="sidebar-toggle-box">
        <div class="fa fa-bars"></div>
    </div>
</div>
<!--logo end-->

<div class="top-nav clearfix">
    <!--search & user info start-->
    <ul class="nav pull-right top-menu">
        <li>
            <input type="text" class="form-control search" placeholder=" Search">
        </li>
        <!-- user login dropdown start-->
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="static/images/2.png">
                <span class="username">{{user.username}}</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                
                <li><a href="{% url 'user_logout' %}"><i class="fa fa-key"></i> Log Out</a></li>
            </ul>
        </li>
        <!-- user login dropdown end -->
       
    </ul>
    <!--search & user info end-->
</div>
</header>
<!--header end-->
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse">
        <!-- sidebar menu start-->
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="active" href="{% url 'dashboard' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
				{% if user.is_superuser %}
				<li>
                    <a class="active" href="{% url 'admin:index' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Admin</span>
                    </a>
                </li>

                <li>
                    <a class="active" href="{% url 'view_service_booking' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Service Request</span>
                    </a>
                </li>
				{% endif %}
                
                {% if user.userregister %}
                <li>
                    <a href="{% url 'booking_services' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Service Booking </span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'my_bookings' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>View My Bookings</span>
                    </a>
                </li>


				<li>
                    <a href="{% url 'send_complaint' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Send Complaints</span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'my_complaints' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>My Complaints</span>
                    </a>
                </li>

				{% endif %}
				{% if user.employeeregister %}
				<li>
                    <a href="{% url 'allotted_work' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>My Works</span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'allotted_complaints' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Allotted Complaints</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'change_status' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Change Status</span>
                    </a>
                </li>
				{% endif %}



                
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-envelope"></i>
                        <span>Mail </span>
                    </a>
                    <ul class="sub">
                        <li><a href="mail.html">Inbox</a></li>
                        <li><a href="mail_compose.html">Compose Mail</a></li>
                    </ul>
                </li>
                
            </ul>            </div>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->
{% block content %}

{% endblock %}
 <!-- footer -->
		  <div class="footer">
			<div class="wthree-copyright">
			  <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
			</div>
		  </div>
  <!-- / footer -->
</section>
<!--main content end-->
</section>
<script src="static/js/bootstrap.js"></script>
<script src="static/js/jquery.dcjqaccordion.2.7.js"></script>
<script src="static/js/scripts.js"></script>
<script src="static/js/jquery.slimscroll.js"></script>
<script src="static/js/jquery.nicescroll.js"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
<script src="static/js/jquery.scrollTo.js"></script>
<!-- morris JavaScript -->	
<script>
	$(document).ready(function() {
		//BOX BUTTON SHOW AND CLOSE
	   jQuery('.small-graph-box').hover(function() {
		  jQuery(this).find('.box-button').fadeIn('fast');
	   }, function() {
		  jQuery(this).find('.box-button').fadeOut('fast');
	   });
	   jQuery('.small-graph-box .box-close').click(function() {
		  jQuery(this).closest('.small-graph-box').fadeOut(200);
		  return false;
	   });
	   
	    //CHARTS
	    function gd(year, day, month) {
			return new Date(year, month - 1, day).getTime();
		}
		
		graphArea2 = Morris.Area({
			element: 'hero-area',
			padding: 10,
        behaveLikeLine: true,
        gridEnabled: false,
        gridLineColor: '#dddddd',
        axes: true,
        resize: true,
        smooth:true,
        pointSize: 0,
        lineWidth: 0,
        fillOpacity:0.85,
			data: [
				{period: '2015 Q1', iphone: 2668, ipad: null, itouch: 2649},
				{period: '2015 Q2', iphone: 15780, ipad: 13799, itouch: 12051},
				{period: '2015 Q3', iphone: 12920, ipad: 10975, itouch: 9910},
				{period: '2015 Q4', iphone: 8770, ipad: 6600, itouch: 6695},
				{period: '2016 Q1', iphone: 10820, ipad: 10924, itouch: 12300},
				{period: '2016 Q2', iphone: 9680, ipad: 9010, itouch: 7891},
				{period: '2016 Q3', iphone: 4830, ipad: 3805, itouch: 1598},
				{period: '2016 Q4', iphone: 15083, ipad: 8977, itouch: 5185},
				{period: '2017 Q1', iphone: 10697, ipad: 4470, itouch: 2038},
			
			],
			lineColors:['#eb6f6f','#926383','#eb6f6f'],
			xkey: 'period',
            redraw: true,
            ykeys: ['iphone', 'ipad', 'itouch'],
            labels: ['All Visitors', 'Returning Visitors', 'Unique Visitors'],
			pointSize: 2,
			hideHover: 'auto',
			resize: true
		});
		
	   
	});
	</script>
<!-- calendar -->
	<script type="text/javascript" src="static/js/monthly.js"></script>
	<script type="text/javascript">
		$(window).load( function() {

			$('#mycalendar').monthly({
				mode: 'event',
				
			});

			$('#mycalendar2').monthly({
				mode: 'picker',
				target: '#mytarget',
				setWidth: '250px',
				startHidden: true,
				showTrigger: '#mytarget',
				stylePast: true,
				disablePast: true
			});

		switch(window.location.protocol) {
		case 'http:':
		case 'https:':
		// running on a server, should be good.
		break;
		case 'file:':
		alert('Just a heads-up, events will not work when run locally.');
		}

		});
	</script>
	<!-- //calendar -->
</body>
</html>

account/templates/my_bookings.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="table-responsive table-shadow" style="background-color: bisque;">
    
  {% if my_booking %}
  <table class="table">
        <thead>
          <tr>
            <!-- <th scope="col">#</th> -->
            <th scope="col">User</th>
            <th scope="col">Phone</th>
            <th scope="col">Allotted Employee</th>
            <th scope="col">Location</th>
            <th scope="col">Wanted date</th>
            <th scope="col">Battery Model</th>
            <th scope="col">Unit</th>
            <th scope="col">Status</th>
            <th scope="col">Booking Date</th>
            <th scope="col">Amount</th>
            <th scope="col">PAY</th>

          </tr>
        </thead>
        <tbody>
            {% for i in my_booking %}
          <tr style="background-color: #d9a3a3;">

            <td>{{ i.user.username}}</td>
            <td>{{ i.user_details.phone}}</td>
            <td>{{ i.employee.user.username }}</td>
            <td>{{ i.location}}</td>
            <td>{{ i.wanted_date}}</td>
            <td>{{ i.battery_type}}</td>
            <td>{{ i.unit}}</td>
            
            {% if i.booking_status == 'processing' %}
            <td style="color:rgb(235, 78, 16);font-weight: bold">{{ i.booking_status }}</td>
            {% endif %}
            {% if i.booking_status == 'accepted' %}
            <td style="color:rgb(16, 235, 16);font-weight: bold">{{ i.booking_status }}</td>
            {% endif %}
            {% if i.booking_status == 'rejected' %}
            <td style="color:rgb(235, 16, 16);font-weight: bold">{{ i.booking_status }}</td>
            {% endif %}
            <td>{{ i.date }}</td>
            <td>{{ i.amount }}</td>
            {% if i.paid == True %}
            <td>Paid</td>
            {% else %}
            <td><a href="{% url 'payment:payment' i.id %}">PAY</a></td>
            {% endif %}

           
          </tr>

          {% endfor %}

        </tbody>

  </table>
  {% else %}

  <span>No Leaves can be found...</span>
  {% endif %}

</div>

{% endblock %}