account/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',views.index,name='index'),
    path('user_register',views.user_register,name='user_register'),
    path('employee_register',views.employee_register,name='employee_register'),
    path('user_login',views.user_login,name='user_login'),
    path('user_logout',views.user_logout,name='user_logout'),
    path('dashboard',views.dashboard,name='dashboard'),


    path('booking_services',views.booking_services,name='booking_services'),
    path('my_bookings',views.my_bookings,name='my_bookings'),
    path('allotted_work',views.allotted_work,name='allotted_work'),

    path('send_complaint',views.send_complaint,name='send_complaint'),
    path('my_complaints',views.my_complaints,name='my_complaints'),
    path('allotted_complaints',views.allotted_complaints,name='allotted_complaints'),


    path('view_service_booking',views.view_service_booking,name='view_service_booking'),

    path('assign_employee/<int:id>',views.assign_employee,name='assign_employee'),

    path('update_booking/<int:id>',views.update_booking,name='update_booking'),
    path('change_status',views.change_status,name='change_status'),

    

    

]

payment/urls.py
from django.urls import path
from .import views

app_name = 'payment'
urlpatterns = [
    path('payment/<int:booking_id>',views.payment,name='payment'),
    path('payment-status', views.payment_status, name='payment-status'),


 
    
]

solar_management/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('payment/',include('payment.urls')),
]

payment/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Payment(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    name=models.CharField(max_length=20)
    amount = models.CharField(max_length=100)
    payment_id=models.CharField(max_length=200,blank=True)
    order_id=models.CharField(max_length=20,blank=True)
    is_paid=models.BooleanField(default=False)
    
    
    def __str__(self):
        
        return str(self.name)

payment/forms.py
from django import forms
from django.db.models import fields
from .models import *
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,Submit

class PaymentForm(forms.ModelForm):
    class Meta:
        model=Payment
        fields = ('amount',)
    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.helper=FormHelper(self)
    #     self.helper.layout=Layout(
    #         'name',
    #         'amount',
    #         Submit('submit','Pay_Now',css_class='button white btn-block btn-primary')
    #     )

payment/views.py
from .models import *
from django.shortcuts import render
import razorpay
from .forms import PaymentForm
from account.models import *

def payment(request,booking_id):
    booking=Booking.objects.get(id=booking_id)
    amount=booking.amount
    if request.method == "POST":
        booking=Booking.objects.get(id=booking_id)
        amount=booking.amount
        name = request.user
        amount1=amount
        
        amount = int(amount1) *100
        client = razorpay.Client(auth=('rzp_test_48Z9LMTDVAN5JU', 'gMxfhwgZ73ANYJQCeblLMy7W'))
        response_payment = client.order.create(dict(amount=amount,
                                                    currency='INR')
                                               )

        order_id = response_payment['id']
        order_status = response_payment['status']
        
        if order_status == 'created':
            payment = Payment(
                user=request.user,
                name=name,
                amount=amount1,
                order_id=order_id,
                
               
            )
          
        payment.save()
        booking=Booking.objects.update_or_create(id=booking_id,
        defaults={'paid':True}
        )
        
        response_payment['name'] = name

        form = PaymentForm(request.POST or None)
        return render(request, 'payment/payment.html', {'form':form,'payment': response_payment,'amount':amount1})

    form = PaymentForm()
    return render(request, 'payment/payment.html', {'form': form,'amount':amount})


def payment_status(request):
    response = request.POST
    params_dict = {

       'razorpay_order_id': response['razorpay_order_id'],
       'razorpay_payment_id': response['razorpay_payment_id'],
       'razorpay_signature': response['razorpay_signature'],
     
    }

    # client instance
    client = razorpay.Client(auth=('rzp_test_48Z9LMTDVAN5JU', 'gMxfhwgZ73ANYJQCeblLMy7W'))
    

    try:
        status = client.utility.verify_payment_signature(params_dict)
        payment = Payment.objects.get(order_id=response['razorpay_order_id'])
        payment.payment_id = response['razorpay_payment_id']
        payment.user=request.user
        payment.is_paid = True
        payment.save()

       
        
        return render(request, 'payment/payment_status.html', {'status': True,'payment_id':payment.payment_id})
    except:
        return render(request, 'payment/payment_status.html', {'status': False})

templates/payment/payment.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<head>
<title>Visitors an Admin Panel Category Bootstrap Responsive Website Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- bootstrap-css -->
<link rel="stylesheet" href="/static/css/bootstrap.min.css" >
<!-- //bootstrap-css -->
<!-- Custom CSS -->
<link href="/static/css/style1.css" rel='stylesheet' type='text/css' />
<link href="/static/css/style-responsive.css" rel="stylesheet"/>
<!-- font CSS -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<!-- font-awesome icons -->
<link rel="stylesheet" href="/static/css/font.css" type="text/css"/>
<link href="/static/css/font-awesome.css" rel="stylesheet"> 
<link rel="stylesheet" href="/static/css/morris.css" type="text/css"/>
<!-- calendar -->
<link rel="stylesheet" href="/static/css/monthly.css">
<!-- //calendar -->
<!-- //font-awesome icons -->
<script src="/static/js/jquery2.0.3.min.js"></script>
<script src="/static/js/raphael-min.js"></script>
<script src="/static/js/morris.js"></script>
</head>
<body>
<section id="container">
<!--header start-->
<header class="header  clearfix">
<!--logo start-->
<div class="brand">
    <a href="{% url 'index' %}" class="logo">
        SOLAR
    </a>
    <div class="sidebar-toggle-box">
        <div class="fa fa-bars"></div>
    </div>
</div>
<!--logo end-->

<div class="top-nav clearfix">
    <!--search & user info start-->
    <ul class="nav pull-right top-menu">
        <li>
            <input type="text" class="form-control search" placeholder=" Search">
        </li>
        <!-- user login dropdown start-->
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="/static/images/2.png">
                <span class="username">{{user.username}}</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                
                <li><a href="{% url 'user_logout' %}"><i class="fa fa-key"></i> Log Out</a></li>
            </ul>
        </li>
        <!-- user login dropdown end -->
       
    </ul>
    <!--search & user info end-->
</div>
</header>
<!--header end-->
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse">
        <!-- sidebar menu start-->
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="active" href="{% url 'dashboard' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
				{% if user.is_superuser %}
				<li>
                    <a class="active" href="{% url 'admin:index' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Admin</span>
                    </a>
                </li>

                <li>
                    <a class="active" href="{% url 'view_service_booking' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Service Request</span>
                    </a>
                </li>
				{% endif %}
                
                {% if user.userregister %}
                <li>
                    <a href="{% url 'booking_services' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Service Booking </span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'my_bookings' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>View My Bookings</span>
                    </a>
                </li>


				<li>
                    <a href="{% url 'send_complaint' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Send Complaints</span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'my_complaints' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>My Complaints</span>
                    </a>
                </li>

				{% endif %}
				{% if user.employeeregister %}
				<li>
                    <a href="{% url 'allotted_work' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>My Works</span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'allotted_complaints' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Allotted Complaints</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'change_status' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Change Status</span>
                    </a>
                </li>
				{% endif %}



                
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-envelope"></i>
                        <span>Mail </span>
                    </a>
                    <ul class="sub">
                        <li><a href="mail.html">Inbox</a></li>
                        <li><a href="mail_compose.html">Compose Mail</a></li>
                    </ul>
                </li>
                
            </ul>            </div>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->

{% load crispy_forms_tags %}
{% block content %}
<h1>Payment</h1>
<form action="" method="POST">
    {% csrf_token %}
    <div class="container" style="width: 50%; background-color:wheat;border-radius: 5px; padding: 150px;">
        <h2 style="color: tomato;">user name: {{user.username}}</h2>
        <h2 style="color: tomato;">Amount: {{amount}}</h2>

        <input type="submit" value="PAY">
</form>
<br/> {% if payment %}
<form action="{% url 'payment:payment-status' %}" method="POST">
    {% csrf_token %}
   
    <script src="https://checkout.razorpay.com/v1/checkout.js" data-key="rzp_test_48Z9LMTDVAN5JU" data-amount="{{ payment.amount }}" data-currency="{{ payment.currency }}" data-order_id="{{payment.id}}" data-buttontext="Pay with Razorpay" data-name="House Boat Management"
        data-description="Pay Your Money" data-image="https://example.com/your_logo.jpg" data-prefill.name="{{ payment.name }}" data-prefill.email="you@example.com" data-theme.color="#F37254"></script>
    <input type="hidden" custom="Hidden Element" name="hidden">
</form>{% endif %}
</div>{% endblock %}




<div class="footer">
    <div class="wthree-copyright">
      <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
    </div>
  </div>
<!-- / footer -->
</section>
<!--main content end-->
</section>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
<script src="/static/js/scripts.js"></script>
<script src="/static/js/jquery.slimscroll.js"></script>
<script src="/static/js/jquery.nicescroll.js"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
<script src="/static/js/jquery.scrollTo.js"></script>
<!-- morris JavaScript -->	
<script>
$(document).ready(function() {
//BOX BUTTON SHOW AND CLOSE
jQuery('.small-graph-box').hover(function() {
  jQuery(this).find('.box-button').fadeIn('fast');
}, function() {
  jQuery(this).find('.box-button').fadeOut('fast');
});
jQuery('.small-graph-box .box-close').click(function() {
  jQuery(this).closest('.small-graph-box').fadeOut(200);
  return false;
});

//CHARTS
function gd(year, day, month) {
    return new Date(year, month - 1, day).getTime();
}

graphArea2 = Morris.Area({
    element: 'hero-area',
    padding: 10,
behaveLikeLine: true,
gridEnabled: false,
gridLineColor: '#dddddd',
axes: true,
resize: true,
smooth:true,
pointSize: 0,
lineWidth: 0,
fillOpacity:0.85,
    data: [
        {period: '2015 Q1', iphone: 2668, ipad: null, itouch: 2649},
        {period: '2015 Q2', iphone: 15780, ipad: 13799, itouch: 12051},
        {period: '2015 Q3', iphone: 12920, ipad: 10975, itouch: 9910},
        {period: '2015 Q4', iphone: 8770, ipad: 6600, itouch: 6695},
        {period: '2016 Q1', iphone: 10820, ipad: 10924, itouch: 12300},
        {period: '2016 Q2', iphone: 9680, ipad: 9010, itouch: 7891},
        {period: '2016 Q3', iphone: 4830, ipad: 3805, itouch: 1598},
        {period: '2016 Q4', iphone: 15083, ipad: 8977, itouch: 5185},
        {period: '2017 Q1', iphone: 10697, ipad: 4470, itouch: 2038},
    
    ],
    lineColors:['#eb6f6f','#926383','#eb6f6f'],
    xkey: 'period',
    redraw: true,
    ykeys: ['iphone', 'ipad', 'itouch'],
    labels: ['All Visitors', 'Returning Visitors', 'Unique Visitors'],
    pointSize: 2,
    hideHover: 'auto',
    resize: true
});


});
</script>
<!-- calendar -->
<script type="text/javascript" src="/static/js/monthly.js"></script>
<script type="text/javascript">
$(window).load( function() {

    $('#mycalendar').monthly({
        mode: 'event',
        
    });

    $('#mycalendar2').monthly({
        mode: 'picker',
        target: '#mytarget',
        setWidth: '250px',
        startHidden: true,
        showTrigger: '#mytarget',
        stylePast: true,
        disablePast: true
    });

switch(window.location.protocol) {
case 'http:':
case 'https:':
// running on a server, should be good.
break;
case 'file:':
alert('Just a heads-up, events will not work when run locally.');
}

});
</script>
<!-- //calendar -->
</body>
</html>

templates/payment/payment_status.html
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<head>
<title>Visitors an Admin Panel Category Bootstrap Responsive Website Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- bootstrap-css -->
<link rel="stylesheet" href="/static/css/bootstrap.min.css" >
<!-- //bootstrap-css -->
<!-- Custom CSS -->
<link href="/static/css/style1.css" rel='stylesheet' type='text/css' />
<link href="/static/css/style-responsive.css" rel="stylesheet"/>
<!-- font CSS -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<!-- font-awesome icons -->
<link rel="stylesheet" href="/static/css/font.css" type="text/css"/>
<link href="/static/css/font-awesome.css" rel="stylesheet"> 
<link rel="stylesheet" href="/static/css/morris.css" type="text/css"/>
<!-- calendar -->
<link rel="stylesheet" href="/static/css/monthly.css">
<!-- //calendar -->
<!-- //font-awesome icons -->
<script src="/static/js/jquery2.0.3.min.js"></script>
<script src="/static/js/raphael-min.js"></script>
<script src="/static/js/morris.js"></script>
</head>
<body>
<section id="container">
<!--header start-->
<header class="header  clearfix">
<!--logo start-->
<div class="brand">
    <a href="{% url 'index' %}" class="logo">
        SOLAR
    </a>
    <div class="sidebar-toggle-box">
        <div class="fa fa-bars"></div>
    </div>
</div>
<!--logo end-->

<div class="top-nav clearfix">
    <!--search & user info start-->
    <ul class="nav pull-right top-menu">
        <li>
            <input type="text" class="form-control search" placeholder=" Search">
        </li>
        <!-- user login dropdown start-->
        <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <img alt="" src="/static/images/2.png">
                <span class="username">{{user.username}}</span>
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu extended logout">
                <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                
                <li><a href="{% url 'user_logout' %}"><i class="fa fa-key"></i> Log Out</a></li>
            </ul>
        </li>
        <!-- user login dropdown end -->
       
    </ul>
    <!--search & user info end-->
</div>
</header>
<!--header end-->
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse">
        <!-- sidebar menu start-->
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="active" href="{% url 'dashboard' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
				{% if user.is_superuser %}
				<li>
                    <a class="active" href="{% url 'admin:index' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Admin</span>
                    </a>
                </li>

                <li>
                    <a class="active" href="{% url 'view_service_booking' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Service Request</span>
                    </a>
                </li>
				{% endif %}
                
                {% if user.userregister %}
                <li>
                    <a href="{% url 'booking_services' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Service Booking </span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'my_bookings' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>View My Bookings</span>
                    </a>
                </li>


				<li>
                    <a href="{% url 'send_complaint' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Send Complaints</span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'my_complaints' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>My Complaints</span>
                    </a>
                </li>

				{% endif %}
				{% if user.employeeregister %}
				<li>
                    <a href="{% url 'allotted_work' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>My Works</span>
                    </a>
                </li>
				<li>
                    <a href="{% url 'allotted_complaints' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Allotted Complaints</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'change_status' %}">
                        <i class="fa fa-bullhorn"></i>
                        <span>Change Status</span>
                    </a>
                </li>
				{% endif %}



                
                <li class="sub-menu">
                    <a href="javascript:;">
                        <i class="fa fa-envelope"></i>
                        <span>Mail </span>
                    </a>
                    <ul class="sub">
                        <li><a href="mail.html">Inbox</a></li>
                        <li><a href="mail_compose.html">Compose Mail</a></li>
                    </ul>
                </li>
                
            </ul>            </div>
        <!-- sidebar menu end-->
    </div>
</aside>
<!--sidebar end-->
{% block content %}
 {% if status %}
<div class="container" style="text-align: center;">
    <i class="fa fa-check-circle" aria-hidden="true" style="font-size: 80px; color: green;"></i>
</div>
<h4 style="text-align: center;">Thank you. Your payment was successful. Your payment Id is:{{payment_id}}</h4>
{% else %}
<h2 style="text-align: center;">Your Payment is failed! Try again.</h2>
{% endif %} 
{% endblock %}

<div class="footer">
    <div class="wthree-copyright">
      <p>© 2017 Visitors. All rights reserved | Design by <a href="http://w3layouts.com">W3layouts</a></p>
    </div>
  </div>
<!-- / footer -->
</section>
<!--main content end-->
</section>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
<script src="/static/js/scripts.js"></script>
<script src="/static/js/jquery.slimscroll.js"></script>
<script src="/static/js/jquery.nicescroll.js"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
<script src="/static/js/jquery.scrollTo.js"></script>
<!-- morris JavaScript -->	
<script>
$(document).ready(function() {
//BOX BUTTON SHOW AND CLOSE
jQuery('.small-graph-box').hover(function() {
  jQuery(this).find('.box-button').fadeIn('fast');
}, function() {
  jQuery(this).find('.box-button').fadeOut('fast');
});
jQuery('.small-graph-box .box-close').click(function() {
  jQuery(this).closest('.small-graph-box').fadeOut(200);
  return false;
});

//CHARTS
function gd(year, day, month) {
    return new Date(year, month - 1, day).getTime();
}

graphArea2 = Morris.Area({
    element: 'hero-area',
    padding: 10,
behaveLikeLine: true,
gridEnabled: false,
gridLineColor: '#dddddd',
axes: true,
resize: true,
smooth:true,
pointSize: 0,
lineWidth: 0,
fillOpacity:0.85,
    data: [
        {period: '2015 Q1', iphone: 2668, ipad: null, itouch: 2649},
        {period: '2015 Q2', iphone: 15780, ipad: 13799, itouch: 12051},
        {period: '2015 Q3', iphone: 12920, ipad: 10975, itouch: 9910},
        {period: '2015 Q4', iphone: 8770, ipad: 6600, itouch: 6695},
        {period: '2016 Q1', iphone: 10820, ipad: 10924, itouch: 12300},
        {period: '2016 Q2', iphone: 9680, ipad: 9010, itouch: 7891},
        {period: '2016 Q3', iphone: 4830, ipad: 3805, itouch: 1598},
        {period: '2016 Q4', iphone: 15083, ipad: 8977, itouch: 5185},
        {period: '2017 Q1', iphone: 10697, ipad: 4470, itouch: 2038},
    
    ],
    lineColors:['#eb6f6f','#926383','#eb6f6f'],
    xkey: 'period',
    redraw: true,
    ykeys: ['iphone', 'ipad', 'itouch'],
    labels: ['All Visitors', 'Returning Visitors', 'Unique Visitors'],
    pointSize: 2,
    hideHover: 'auto',
    resize: true
});


});
</script>
<!-- calendar -->
<script type="text/javascript" src="/static/js/monthly.js"></script>
<script type="text/javascript">
$(window).load( function() {

    $('#mycalendar').monthly({
        mode: 'event',
        
    });

    $('#mycalendar2').monthly({
        mode: 'picker',
        target: '#mytarget',
        setWidth: '250px',
        startHidden: true,
        showTrigger: '#mytarget',
        stylePast: true,
        disablePast: true
    });

switch(window.location.protocol) {
case 'http:':
case 'https:':
// running on a server, should be good.
break;
case 'file:':
alert('Just a heads-up, events will not work when run locally.');
}

});
</script>
<!-- //calendar -->
</body>
</html>

templates/payment/process.html
<html>{% load static %}{% block title %}product pag{% endblock %}{% load crispy_forms_tags %} {% block content %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="static/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/static/css/font-awesome.css">
<link rel='stylesheet' id='camera-css' href='/static/css/camera.css' type='text/css' media='all'>

<link rel="stylesheet" type="text/css" href="/static/css/slicknav.css">
<link rel="stylesheet" href="/static/css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
<link rel="stylesheet" type="text/css" href="/static/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/css/card.css">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script type="text/javascript" src="/static/js/jquery-1.8.3.min.js"></script>

<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700|Open+Sans:700' rel='stylesheet' type='text/css'>
<script type="text/javascript" src="/static/js/jquery.mobile.customized.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="/static/js/camera.min.js"></script>
<script type="text/javascript" src="/static/js/myscript.js"></script>
<script src="/static/js/sorting.js" type="text/javascript"></script>
<script src="/static/js/jquery.isotope.js" type="text/javascript"></script>
<!--script type="text/javascript" src="static/js/jquery.nav.js"></script-->
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
     <link rel="stylesheet" href="static/css/login_style.css"-->


<script>
    jQuery(function() {
        jQuery('#camera_wrap_1').camera({
            transPeriod: 500,
            time: 3000,
            height: '490px',
            thumbnails: false,
            pagination: true,
            playPause: false,
            loader: false,
            navigation: false,
            hover: false
        });
        status
    });
</script>
<buttton><a href="">Cash on delivary Please contact with branch phone number</a></buttton>

<button class="paybutton"><a href="{% url 'payment:payment' %}">Pay Now</a></button> {% endblock %}
</html>